<?php


namespace App\Definitions;


use App\Database\Schema\CachableDefinition;
use App\Database\Schema\Definition;
use Illuminate\Contracts\Support\Arrayable;
use Illuminate\Support\Collection;

/**
 * Class Quest
 *
 * @package App\Definitions
 *
 * @property-read string $name
 * @property-read string $title
 * @property-read string $image
 * @property-read bool $background
 * @property-read int $difficulty
 * @property-read array $restrictions
 * @property-read array $objectives
 * @property-read array $rewards
 */
class EconQuest extends CachableDefinition
{
	/**
	 * @var string
	 */
	protected string $location = 'economy/contracker/quests.json';

	public function fill (array|Arrayable $arr) : Definition
	{
		$arr['image'] = isset($arr['image'])
			? '//creators.tf/cdn/'.substr ($arr['image'], 6)
			: '';
		return parent::fill ($arr); // TODO: Change the autogenerated stub
	}

	/**
	 * Applies any necessary transformations to obtain our data.
	 *
	 * @param  array  $original
	 * @return array
	 */
	protected function locate (Collection $original) : array
	{
		return $original
			->where ('title', $this->id)
			->first ();
	}

}
